### ISSUE TITLE
Need more detailed comments throughout the scripts

### ISSUE THREAD

**Issue by aleksandrPi** [plantformatics/maize_single_cell_cis_regulatory_atlas#2]
Hi, wonderful paper. However, I have an issue navigating through the workflow of your scripts. Would it be possible to include more detailed description of each of the steps? You are not extensively relying on the more established Seurat and Monocle packages, which is refreshing, however, makes it more difficult to understand the tools you have defined and been using. Thanks!

**Comment by plantformatics** [comment]
Hi @aleksandrPi, 

Thank you for the comments; generating analytical tools from scratch certainly does not come without challenges. While these scripts are currently provided as is, we are working to aggregate them into a standalone package. I realize its not exactly straight forward, but in the meantime, I would suggest reviewing the function source code from steps that aren't clear. I think a big hurdle for a lot of people will be the myriad parameters. Future updates to these scripts will fix parameters that have negligible or no effect on results. I hoped to have clarified that I wrote these scripts for our use case. Re-writing the source to be more modular/flexible is another point of emphasis for the near future. A tutorial with example data is on the docket as well. 

Which specific functions/steps are you interested in?
