### ISSUE TITLE
Details about Phenotypic variance relative enrichment. 

### ISSUE THREAD

**Issue by Myrtle-bio** [plantformatics/maize_single_cell_cis_regulatory_atlas#4]
Thank you very much for sharing the analysis code! I have a question about a detail seems not to be involved in these manuscripts or published papers. 

![image](https://github.com/plantformatics/maize_single_cell_cis_regulatory_atlas/assets/148927074/bbcc5690-1bbe-4d0e-bb23-c7ad9b6e2159)

In this image, you mentioned 
> Cell-type-specific ACRs were associated with a lower density of polymorphisms compared to nonspecific ACRs (Figure 3G). 
> However, genetic variants embedded within cell-type-specific ACRs were more frequently associated with phenotypic variation determined by genome-wide association studies .

Could you please provide more detailed explanation of how the y-axis was calculated in this figure?  What's the defination of relative enrichment? It would be greatly heplful if you can upload the plotting code as well. Thank you! Have a nice weekend!

**Comment by plantformatics** [comment]
We used the same method as in Fig. 1 of this paper: https://www.nature.com/articles/s41477-019-0547-0

Hope this helps

**Comment by Myrtle-bio** [comment]
It helpes a lot, thanks!
